# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CMake.app/Contents/bin/cmake

# The command to remove a file.
RM = /Applications/CMake.app/Contents/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/esil/projects/ligero/src/ligetron

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/esil/projects/ligero/build/ligetron-wasm

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/Applications/CMake.app/Contents/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/Applications/CMake.app/Contents/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/Applications/CMake.app/Contents/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/esil/projects/ligero/build/ligetron-wasm/CMakeFiles /Users/esil/projects/ligero/build/ligetron-wasm//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/esil/projects/ligero/build/ligetron-wasm/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -P /Users/esil/projects/ligero/build/ligetron-wasm/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named logging

# Build rule for target.
logging: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 logging
.PHONY : logging

# fast build rule for target.
logging/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logging.dir/build.make CMakeFiles/logging.dir/build
.PHONY : logging/fast

#=============================================================================
# Target rules for targets named bn254

# Build rule for target.
bn254: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bn254
.PHONY : bn254

# fast build rule for target.
bn254/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn254.dir/build.make CMakeFiles/bn254.dir/build
.PHONY : bn254/fast

#=============================================================================
# Target rules for targets named portable_archive

# Build rule for target.
portable_archive: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 portable_archive
.PHONY : portable_archive

# fast build rule for target.
portable_archive/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/portable_archive.dir/build.make CMakeFiles/portable_archive.dir/build
.PHONY : portable_archive/fast

#=============================================================================
# Target rules for targets named webgpu_engine

# Build rule for target.
webgpu_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webgpu_engine
.PHONY : webgpu_engine

# fast build rule for target.
webgpu_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/build
.PHONY : webgpu_engine/fast

#=============================================================================
# Target rules for targets named webgpu_prover

# Build rule for target.
webgpu_prover: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webgpu_prover
.PHONY : webgpu_prover

# fast build rule for target.
webgpu_prover/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_prover.dir/build.make CMakeFiles/webgpu_prover.dir/build
.PHONY : webgpu_prover/fast

#=============================================================================
# Target rules for targets named webgpu_verifier

# Build rule for target.
webgpu_verifier: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 webgpu_verifier
.PHONY : webgpu_verifier

# fast build rule for target.
webgpu_verifier/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_verifier.dir/build.make CMakeFiles/webgpu_verifier.dir/build
.PHONY : webgpu_verifier/fast

#=============================================================================
# Target rules for targets named test_mpz_get

# Build rule for target.
test_mpz_get: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_mpz_get
.PHONY : test_mpz_get

# fast build rule for target.
test_mpz_get/fast:
	$(MAKE) $(MAKESILENT) -f tests/util/CMakeFiles/test_mpz_get.dir/build.make tests/util/CMakeFiles/test_mpz_get.dir/build
.PHONY : test_mpz_get/fast

#=============================================================================
# Target rules for targets named run_mpz_util_tests

# Build rule for target.
run_mpz_util_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_mpz_util_tests
.PHONY : run_mpz_util_tests

# fast build rule for target.
run_mpz_util_tests/fast:
	$(MAKE) $(MAKESILENT) -f tests/util/CMakeFiles/run_mpz_util_tests.dir/build.make tests/util/CMakeFiles/run_mpz_util_tests.dir/build
.PHONY : run_mpz_util_tests/fast

include/util/boost/portable_binary_iarchive.o: include/util/boost/portable_binary_iarchive.cpp.o
.PHONY : include/util/boost/portable_binary_iarchive.o

# target to build an object file
include/util/boost/portable_binary_iarchive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/portable_archive.dir/build.make CMakeFiles/portable_archive.dir/include/util/boost/portable_binary_iarchive.cpp.o
.PHONY : include/util/boost/portable_binary_iarchive.cpp.o

include/util/boost/portable_binary_iarchive.i: include/util/boost/portable_binary_iarchive.cpp.i
.PHONY : include/util/boost/portable_binary_iarchive.i

# target to preprocess a source file
include/util/boost/portable_binary_iarchive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/portable_archive.dir/build.make CMakeFiles/portable_archive.dir/include/util/boost/portable_binary_iarchive.cpp.i
.PHONY : include/util/boost/portable_binary_iarchive.cpp.i

include/util/boost/portable_binary_iarchive.s: include/util/boost/portable_binary_iarchive.cpp.s
.PHONY : include/util/boost/portable_binary_iarchive.s

# target to generate assembly for a file
include/util/boost/portable_binary_iarchive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/portable_archive.dir/build.make CMakeFiles/portable_archive.dir/include/util/boost/portable_binary_iarchive.cpp.s
.PHONY : include/util/boost/portable_binary_iarchive.cpp.s

include/util/boost/portable_binary_oarchive.o: include/util/boost/portable_binary_oarchive.cpp.o
.PHONY : include/util/boost/portable_binary_oarchive.o

# target to build an object file
include/util/boost/portable_binary_oarchive.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/portable_archive.dir/build.make CMakeFiles/portable_archive.dir/include/util/boost/portable_binary_oarchive.cpp.o
.PHONY : include/util/boost/portable_binary_oarchive.cpp.o

include/util/boost/portable_binary_oarchive.i: include/util/boost/portable_binary_oarchive.cpp.i
.PHONY : include/util/boost/portable_binary_oarchive.i

# target to preprocess a source file
include/util/boost/portable_binary_oarchive.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/portable_archive.dir/build.make CMakeFiles/portable_archive.dir/include/util/boost/portable_binary_oarchive.cpp.i
.PHONY : include/util/boost/portable_binary_oarchive.cpp.i

include/util/boost/portable_binary_oarchive.s: include/util/boost/portable_binary_oarchive.cpp.s
.PHONY : include/util/boost/portable_binary_oarchive.s

# target to generate assembly for a file
include/util/boost/portable_binary_oarchive.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/portable_archive.dir/build.make CMakeFiles/portable_archive.dir/include/util/boost/portable_binary_oarchive.cpp.s
.PHONY : include/util/boost/portable_binary_oarchive.cpp.s

include/util/log.o: include/util/log.cpp.o
.PHONY : include/util/log.o

# target to build an object file
include/util/log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logging.dir/build.make CMakeFiles/logging.dir/include/util/log.cpp.o
.PHONY : include/util/log.cpp.o

include/util/log.i: include/util/log.cpp.i
.PHONY : include/util/log.i

# target to preprocess a source file
include/util/log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logging.dir/build.make CMakeFiles/logging.dir/include/util/log.cpp.i
.PHONY : include/util/log.cpp.i

include/util/log.s: include/util/log.cpp.s
.PHONY : include/util/log.s

# target to generate assembly for a file
include/util/log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/logging.dir/build.make CMakeFiles/logging.dir/include/util/log.cpp.s
.PHONY : include/util/log.cpp.s

src/bn254.o: src/bn254.cpp.o
.PHONY : src/bn254.o

# target to build an object file
src/bn254.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn254.dir/build.make CMakeFiles/bn254.dir/src/bn254.cpp.o
.PHONY : src/bn254.cpp.o

src/bn254.i: src/bn254.cpp.i
.PHONY : src/bn254.i

# target to preprocess a source file
src/bn254.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn254.dir/build.make CMakeFiles/bn254.dir/src/bn254.cpp.i
.PHONY : src/bn254.cpp.i

src/bn254.s: src/bn254.cpp.s
.PHONY : src/bn254.s

# target to generate assembly for a file
src/bn254.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bn254.dir/build.make CMakeFiles/bn254.dir/src/bn254.cpp.s
.PHONY : src/bn254.cpp.s

src/webgpu/buffer_binding.o: src/webgpu/buffer_binding.cpp.o
.PHONY : src/webgpu/buffer_binding.o

# target to build an object file
src/webgpu/buffer_binding.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/buffer_binding.cpp.o
.PHONY : src/webgpu/buffer_binding.cpp.o

src/webgpu/buffer_binding.i: src/webgpu/buffer_binding.cpp.i
.PHONY : src/webgpu/buffer_binding.i

# target to preprocess a source file
src/webgpu/buffer_binding.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/buffer_binding.cpp.i
.PHONY : src/webgpu/buffer_binding.cpp.i

src/webgpu/buffer_binding.s: src/webgpu/buffer_binding.cpp.s
.PHONY : src/webgpu/buffer_binding.s

# target to generate assembly for a file
src/webgpu/buffer_binding.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/buffer_binding.cpp.s
.PHONY : src/webgpu/buffer_binding.cpp.s

src/webgpu/buffer_view.o: src/webgpu/buffer_view.cpp.o
.PHONY : src/webgpu/buffer_view.o

# target to build an object file
src/webgpu/buffer_view.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/buffer_view.cpp.o
.PHONY : src/webgpu/buffer_view.cpp.o

src/webgpu/buffer_view.i: src/webgpu/buffer_view.cpp.i
.PHONY : src/webgpu/buffer_view.i

# target to preprocess a source file
src/webgpu/buffer_view.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/buffer_view.cpp.i
.PHONY : src/webgpu/buffer_view.cpp.i

src/webgpu/buffer_view.s: src/webgpu/buffer_view.cpp.s
.PHONY : src/webgpu/buffer_view.s

# target to generate assembly for a file
src/webgpu/buffer_view.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/buffer_view.cpp.s
.PHONY : src/webgpu/buffer_view.cpp.s

src/webgpu/common.o: src/webgpu/common.cpp.o
.PHONY : src/webgpu/common.o

# target to build an object file
src/webgpu/common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/common.cpp.o
.PHONY : src/webgpu/common.cpp.o

src/webgpu/common.i: src/webgpu/common.cpp.i
.PHONY : src/webgpu/common.i

# target to preprocess a source file
src/webgpu/common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/common.cpp.i
.PHONY : src/webgpu/common.cpp.i

src/webgpu/common.s: src/webgpu/common.cpp.s
.PHONY : src/webgpu/common.s

# target to generate assembly for a file
src/webgpu/common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/common.cpp.s
.PHONY : src/webgpu/common.cpp.s

src/webgpu/device_bignum.o: src/webgpu/device_bignum.cpp.o
.PHONY : src/webgpu/device_bignum.o

# target to build an object file
src/webgpu/device_bignum.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/device_bignum.cpp.o
.PHONY : src/webgpu/device_bignum.cpp.o

src/webgpu/device_bignum.i: src/webgpu/device_bignum.cpp.i
.PHONY : src/webgpu/device_bignum.i

# target to preprocess a source file
src/webgpu/device_bignum.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/device_bignum.cpp.i
.PHONY : src/webgpu/device_bignum.cpp.i

src/webgpu/device_bignum.s: src/webgpu/device_bignum.cpp.s
.PHONY : src/webgpu/device_bignum.s

# target to generate assembly for a file
src/webgpu/device_bignum.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/device_bignum.cpp.s
.PHONY : src/webgpu/device_bignum.cpp.s

src/webgpu/device_context.o: src/webgpu/device_context.cpp.o
.PHONY : src/webgpu/device_context.o

# target to build an object file
src/webgpu/device_context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/device_context.cpp.o
.PHONY : src/webgpu/device_context.cpp.o

src/webgpu/device_context.i: src/webgpu/device_context.cpp.i
.PHONY : src/webgpu/device_context.i

# target to preprocess a source file
src/webgpu/device_context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/device_context.cpp.i
.PHONY : src/webgpu/device_context.cpp.i

src/webgpu/device_context.s: src/webgpu/device_context.cpp.s
.PHONY : src/webgpu/device_context.s

# target to generate assembly for a file
src/webgpu/device_context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/device_context.cpp.s
.PHONY : src/webgpu/device_context.cpp.s

src/webgpu/engine.o: src/webgpu/engine.cpp.o
.PHONY : src/webgpu/engine.o

# target to build an object file
src/webgpu/engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/engine.cpp.o
.PHONY : src/webgpu/engine.cpp.o

src/webgpu/engine.i: src/webgpu/engine.cpp.i
.PHONY : src/webgpu/engine.i

# target to preprocess a source file
src/webgpu/engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/engine.cpp.i
.PHONY : src/webgpu/engine.cpp.i

src/webgpu/engine.s: src/webgpu/engine.cpp.s
.PHONY : src/webgpu/engine.s

# target to generate assembly for a file
src/webgpu/engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/engine.cpp.s
.PHONY : src/webgpu/engine.cpp.s

src/webgpu/powmod_context.o: src/webgpu/powmod_context.cpp.o
.PHONY : src/webgpu/powmod_context.o

# target to build an object file
src/webgpu/powmod_context.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/powmod_context.cpp.o
.PHONY : src/webgpu/powmod_context.cpp.o

src/webgpu/powmod_context.i: src/webgpu/powmod_context.cpp.i
.PHONY : src/webgpu/powmod_context.i

# target to preprocess a source file
src/webgpu/powmod_context.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/powmod_context.cpp.i
.PHONY : src/webgpu/powmod_context.cpp.i

src/webgpu/powmod_context.s: src/webgpu/powmod_context.cpp.s
.PHONY : src/webgpu/powmod_context.s

# target to generate assembly for a file
src/webgpu/powmod_context.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_engine.dir/build.make CMakeFiles/webgpu_engine.dir/src/webgpu/powmod_context.cpp.s
.PHONY : src/webgpu/powmod_context.cpp.s

src/webgpu_prover.o: src/webgpu_prover.cpp.o
.PHONY : src/webgpu_prover.o

# target to build an object file
src/webgpu_prover.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_prover.dir/build.make CMakeFiles/webgpu_prover.dir/src/webgpu_prover.cpp.o
.PHONY : src/webgpu_prover.cpp.o

src/webgpu_prover.i: src/webgpu_prover.cpp.i
.PHONY : src/webgpu_prover.i

# target to preprocess a source file
src/webgpu_prover.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_prover.dir/build.make CMakeFiles/webgpu_prover.dir/src/webgpu_prover.cpp.i
.PHONY : src/webgpu_prover.cpp.i

src/webgpu_prover.s: src/webgpu_prover.cpp.s
.PHONY : src/webgpu_prover.s

# target to generate assembly for a file
src/webgpu_prover.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_prover.dir/build.make CMakeFiles/webgpu_prover.dir/src/webgpu_prover.cpp.s
.PHONY : src/webgpu_prover.cpp.s

src/webgpu_verifier.o: src/webgpu_verifier.cpp.o
.PHONY : src/webgpu_verifier.o

# target to build an object file
src/webgpu_verifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_verifier.dir/build.make CMakeFiles/webgpu_verifier.dir/src/webgpu_verifier.cpp.o
.PHONY : src/webgpu_verifier.cpp.o

src/webgpu_verifier.i: src/webgpu_verifier.cpp.i
.PHONY : src/webgpu_verifier.i

# target to preprocess a source file
src/webgpu_verifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_verifier.dir/build.make CMakeFiles/webgpu_verifier.dir/src/webgpu_verifier.cpp.i
.PHONY : src/webgpu_verifier.cpp.i

src/webgpu_verifier.s: src/webgpu_verifier.cpp.s
.PHONY : src/webgpu_verifier.s

# target to generate assembly for a file
src/webgpu_verifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/webgpu_verifier.dir/build.make CMakeFiles/webgpu_verifier.dir/src/webgpu_verifier.cpp.s
.PHONY : src/webgpu_verifier.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... run_mpz_util_tests"
	@echo "... bn254"
	@echo "... logging"
	@echo "... portable_archive"
	@echo "... test_mpz_get"
	@echo "... webgpu_engine"
	@echo "... webgpu_prover"
	@echo "... webgpu_verifier"
	@echo "... include/util/boost/portable_binary_iarchive.o"
	@echo "... include/util/boost/portable_binary_iarchive.i"
	@echo "... include/util/boost/portable_binary_iarchive.s"
	@echo "... include/util/boost/portable_binary_oarchive.o"
	@echo "... include/util/boost/portable_binary_oarchive.i"
	@echo "... include/util/boost/portable_binary_oarchive.s"
	@echo "... include/util/log.o"
	@echo "... include/util/log.i"
	@echo "... include/util/log.s"
	@echo "... src/bn254.o"
	@echo "... src/bn254.i"
	@echo "... src/bn254.s"
	@echo "... src/webgpu/buffer_binding.o"
	@echo "... src/webgpu/buffer_binding.i"
	@echo "... src/webgpu/buffer_binding.s"
	@echo "... src/webgpu/buffer_view.o"
	@echo "... src/webgpu/buffer_view.i"
	@echo "... src/webgpu/buffer_view.s"
	@echo "... src/webgpu/common.o"
	@echo "... src/webgpu/common.i"
	@echo "... src/webgpu/common.s"
	@echo "... src/webgpu/device_bignum.o"
	@echo "... src/webgpu/device_bignum.i"
	@echo "... src/webgpu/device_bignum.s"
	@echo "... src/webgpu/device_context.o"
	@echo "... src/webgpu/device_context.i"
	@echo "... src/webgpu/device_context.s"
	@echo "... src/webgpu/engine.o"
	@echo "... src/webgpu/engine.i"
	@echo "... src/webgpu/engine.s"
	@echo "... src/webgpu/powmod_context.o"
	@echo "... src/webgpu/powmod_context.i"
	@echo "... src/webgpu/powmod_context.s"
	@echo "... src/webgpu_prover.o"
	@echo "... src/webgpu_prover.i"
	@echo "... src/webgpu_prover.s"
	@echo "... src/webgpu_verifier.o"
	@echo "... src/webgpu_verifier.i"
	@echo "... src/webgpu_verifier.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -P /Users/esil/projects/ligero/build/ligetron-wasm/CMakeFiles/VerifyGlobs.cmake
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

